pool: { vmImage: 'ubuntu-latest' }
steps:
  - task: NodeTool@0
    displayName: Node install
    inputs: { versionSpec: '10.x' }
  - script: npm install -g npm@latest
    displayName: update NPM
  - task: Npm@1
    displayName: NPM install
    inputs: { command: 'install' }
  - script: npm run all
    displayName: NPM run all
  - script: >-
      rm -rf gh-pages &&
      git submodule add --force -b gh-pages https://$(github_access_token)@github.com/DevSnicket/Eunice.git gh-pages &&
      rm -f -rf gh-pages/arrows &&
      mkdir gh-pages/arrows &&
      cp getSvgElementForStack/createArrows/test/withUse/testCases/default-height.svg gh-pages/arrows &&
      cp getSvgElementForStack/createArrows/test/withUse/testCases/with-descriptions.svg gh-pages/arrows &&
      rm -f -rf gh-pages/examples &&
      mkdir gh-pages/examples &&
      mkdir gh-pages/examples/independency &&
      cp getSvgForYaml/testCases/independency/first-depends-upon-second/expected.svg gh-pages/examples/independency/first-depends-upon-second.svg &&
      cp getSvgForYaml/testCases/independency/first-item-depends-upon-second-item/expected.svg gh-pages/examples/independency/first-item-depends-upon-second-item.svg &&
      cp getSvgForYaml/testCases/independency/two-interdependent/expected.svg gh-pages/examples/independency/two-interdependent.svg &&
      cp getSvgForYaml/testCases/item-depends-upon-parent/expected.svg gh-pages/examples/item-depends-upon-parent.svg &&
      cp getSvgForYaml/testCases/parent-depends-upon-item/expected.svg gh-pages/examples/parent-depends-upon-item.svg &&
      mkdir gh-pages/examples/stack &&
      cp getSvgForYaml/testCases/stack/lower-depends-upon-upper/expected.svg gh-pages/examples/stack/lower-depends-upon-upper.svg &&
      cp getSvgForYaml/testCases/stack/two-interdependent/expected.svg gh-pages/examples/stack/two-interdependent.svg &&
      cp getSvgForYaml/testCases/stack/upper-depends-upon-lower/expected.svg gh-pages/examples/stack/upper-depends-upon-lower.svg &&
      cp getSvgForYaml/testCases/two/expected.svg gh-pages/examples/two.svg &&
      cp getSvgForYaml/withSubset.testCases/upper-item-depends-upon-lower-item-with-parent.svg gh-pages/examples &&
      cd gh-pages &&
      git add . &&
      git config --add user.email grahamdyson@hotmail.com &&
      git config --add user.name "GitHub pages publish" &&
      if [[ `git status --porcelain` ]]; then
        git commit -m "dogfooding and JavaScript harness";
        git push;
      fi
    displayName: GitHub pages publish
  - task: Npm@1
    continueOnError: true
    displayName: NPM publish
    inputs:
      command: 'publish'
      publishEndpoint: 'Azure private NPM'
trigger: [ master ]