pool:
  name: $(pool_name)
  vmImage: ubuntu-18.04
steps:
  - task: NodeTool@0
    displayName: Node install
    inputs: { versionSpec: '10.x' }
  - script: npm install -g npm@latest
    displayName: update NPM
  - task: Npm@1
    displayName: NPM install
    inputs: { command: 'install' }
  - script: npm run all
    displayName: NPM run all
  - task: ShellScript@2
    displayName: website update
    inputs:
      args: $(github_access_token)
      scriptPath: website-update.sh
  - task: Npm@1
    continueOnError: true
    displayName: NPM publish
    inputs:
      command: 'publish'
      publishEndpoint: 'Azure private NPM'
trigger: [ master ]
workspace: { clean: all }