pool:
  name: $(pool_name)
  vmImage: 'ubuntu-latest'
steps:
  - task: UseDotNet@2
    displayName: .NET Core 3.1.x
    inputs:
      version: 3.1.x
      packageType: sdk
  - task: NodeTool@0
    displayName: Node install
    inputs: { versionSpec: '10.x' }
  - task: ShellScript@2
    displayName: download and extract interactive package
    inputs: { scriptPath: WriteInteractiveInDirectoryPathWithYaml/download-and-extract-package.sh }
  - task: ShellScript@2
    displayName: restore test case C# projects
    inputs: { scriptPath: AnalyzeProjectOrSolutionPath/Tests/TestCases/restore.sh }
  - task: ShellScript@2
    displayName: test
    inputs: { scriptPath: test.sh }
  - task: ShellScript@2
    displayName: lint
    inputs: { scriptPath: lint.sh }
  - task: ShellScript@2
    displayName: website update
    inputs:
      args: $(github_access_token)
      scriptPath: website-update.sh
  - task: ShellScript@2
    displayName: spellcheck
    inputs: { scriptPath: spellcheck.sh }
  - task: ShellScript@2
    displayName: spellcheck
    inputs: { scriptPath: package/pack.sh }
  - task: ShellScript@2
    displayName: spellcheck
    inputs: { scriptPath: package/push.sh }
trigger: [ master ]
workspace: { clean: all }