cache:
  directories: [ node_modules ]
deploy:
  - api_key: $NPM_TOKEN
    email: grahamdyson@hotmail.com
    provider: npm
    skip_cleanup: true
  - github-token: $GITHUB_HARNESSES_TOKEN
    keep-history: true
    local-dir: tests/example/output
    on:
      branch: master
    provider: pages
    skip-cleanup: true
    target-branch: gh-pages
install: npm install
language: node_js
node_js: 8.11.2
notifications:
  email:
    on_success: never
    on_failure: always
script: npm run all