pool:
  name: $(pool_name)
  vmImage: 'ubuntu-latest'
steps:
  - task: NodeTool@0
    displayName: Node install
    inputs: { versionSpec: '10.x' }
  - script: npm install -g npm@latest
    displayName: update NPM
  - task: Npm@1
    displayName: NPM install
    inputs: { command: 'install' }
  - script: npm run all
    displayName: NPM run all
  - script: >-
      rm -rf gh-pages &&
      git submodule add --force -b gh-pages https://$(github_access_token)@github.com/DevSnicket/Eunice.git gh-pages &&
      rm -f -rf gh-pages/renderer-test-harness &&
      cp -r tests/example/output gh-pages/renderer-test-harness &&
      rm gh-pages/renderer-test-harness/harness.js.map &&
      cd gh-pages &&
      git add . &&
      git config --add user.email grahamdyson@hotmail.com &&
      git config --add user.name "GitHub pages publish" &&
      if [[ `git status --porcelain` ]]; then
        git commit -m "dogfooding and JavaScript harness";
        git push;
      fi
    displayName: GitHub pages publish
  - task: Npm@1
    continueOnError: true
    displayName: NPM publish
    inputs:
      command: 'publish'
      publishEndpoint: 'Azure private NPM'
trigger: [ master ]