cache:
  directories:
    - node_modules
deploy:
  github-token: $GITHUB_HARNESSES_TOKEN
  keep-history: true
  local-dir: Harnesses/Output
  on:
    branch: master
  provider: pages
  repo: DevSnicket/Eunice-harnesses
  skip-cleanup: true
  target-branch: master
install:
  - npm install
language: node_js
node_js:
  - "8.11.2"
notifications:
  email: false
script:
  - npm run test-travis
  - npm run lint
  - bash ./dogfooding.sh
  - npm run harness