cache:
  directories:
    - node_modules
deploy:
  github-token: $GITHUB_HARNESSES_TOKEN
  keep-history: true
  local-dir: harness/output
  on:
    branch: master
  provider: pages
  skip-cleanup: true
  target-branch: gh-pages
before_install:
  - npm i -g npm@6.1.0
install:
  - (cd harness/javascript-analyzer-and-renderer && npm install)
  - (cd harness/renderer && npm install)
language: node_js
node_js:
  - "8.11.2"
notifications:
  email: false
script:
  - bash dogfooding/generate.sh
  - bash harnesses/lint.sh
  - bash harnesses/build.sh