cache:
  directories:
    - node_modules
before_deploy:
  - cp -r harness/output Harnesses/output
  - cp -r Analyzer/harness/output Harnesses/output/Analyzer
  - cp -r Renderer/harness/output Harnesses/output/Renderer
deploy:
  github-token: $GITHUB_HARNESSES_TOKEN
  keep-history: true
  local-dir: Harnesses/output
  on:
    branch: master
  provider: pages
  repo: DevSnicket/Eunice-harnesses
  skip-cleanup: true
  target-branch: master
install:
  - npm install
  - (cd Analyzer && npm install)
  - (cd callWhenProcessEntryPoint && npm install)
  - (cd dependencyAndStructure && npm install)
  - (cd harness && npm install)
  - (cd Harnesses && npm install)
  - (cd Processors && npm install)
  - (cd Renderer && npm install)
  - (cd Tests && npm install)
language: node_js
node_js:
  - "8.11.2"
notifications:
  email: false
script:
  - npm run lint
  - npm run test
  - (cat Analyzer/test-coverage/lcov.info && cat dependencyAndStructure/test-coverage/lcov.info && cat Processors/test-coverage/lcov.info && cat Renderer/test-coverage/lcov.info) | ./node_modules/coveralls/bin/coveralls.js
  - bash dogfooding/generate.sh
  - npm run harness