cache: { directories: [ node_modules ] }
language: node_js
node_js: 12.16
notifications:
  email:
    on_success: never
    on_failure: always
script:
  - bash ./spellcheck.sh
  - bash ./update-all.sh $GITHUB_HARNESSES_TOKEN
  - bash ./git-push-generated-content.sh $GITHUB_HARNESSES_TOKEN