cache:
  directories:
    - node_modules
deploy:
  keep-history: true
  local-dir: Harnesses
  on:
    branch: master
  provider: pages
    github-token: $GITHUB_HARNESSES_TOKEN
    skip-cleanup: true
language: node_js
node_js:
  - "8.11.2"
notifications:
  email: false
script:
  - npm run test-travis
  - npm run lint
  - npm run harness
  - "./harnesses deploy copy.sh"