cache:
  directories:
    - node_modules
before_deploy:
  - rm -r Harnesses/output
  - cp -r harness/output Harnesses/output
  - cp -r Analyzer/harness/output Harnesses/output/Analyzer
  - cp -r Renderer/harness/output Harnesses/output/Renderer
deploy:
  github-token: $GITHUB_HARNESSES_TOKEN
  keep-history: true
  local-dir: Harnesses/output
  on:
    branch: master
  provider: pages
  repo: DevSnicket/Eunice-harnesses
  skip-cleanup: true
  target-branch: master
install:
  - npm install
language: node_js
node_js:
  - "8.11.2"
notifications:
  email: false
script:
  - npm run test-travis
  - npm run lint
  - bash dogfooding/generate.sh
  - npm run harness