cache:
  directories:
    - node_modules
before_deploy:
  - cp -r harness/output Harnesses/output
  - cp -r javascript-analyzer/harness/output Harnesses/output/javascript-analyzer
  - cp -r Renderer/harness/output Harnesses/output/Renderer
deploy:
  github-token: $GITHUB_HARNESSES_TOKEN
  keep-history: true
  local-dir: Harnesses/output
  on:
    branch: master
  provider: pages
  repo: DevSnicket/Eunice-harnesses
  skip-cleanup: true
  target-branch: master
install:
  - (cd javascript-analyzer && npm install)
  - (cd callWhenProcessEntryPoint && npm install)
  - (cd dependencyAndStructure && npm install)
  - (cd harness && npm install)
  - (cd Harnesses && npm install)
  - (cd Processors && npm install)
  - (cd Renderer && npm install)
  - (cd runTestsFromFileSystem && npm install)
language: node_js
node_js:
  - "8.11.2"
notifications:
  email: false
script:
  - bash lint.sh
  - bash test.sh
  - (mkdir test-coverage && cd test-coverage && echo -n {}>package.json && npm install coveralls@3.0.1 && (cat ../javascript-analyzer/test-coverage/lcov.info && cat ../dependencyAndStructure/test-coverage/lcov.info && cat ../Processors/test-coverage/lcov.info && cat ../Renderer/test-coverage/lcov.info) | ./node_modules/coveralls/bin/coveralls.js)
  - bash dogfooding/generate.sh
  - bash harnesses.sh