cache:
  directories:
    - node_modules
before_deploy:
  - cp -r javascript-analyzer-and-renderer-harness/output harness-output/
  - cp -r Renderer/harness/output harness-output/Renderer
deploy:
  github-token: $GITHUB_HARNESSES_TOKEN
  keep-history: true
  local-dir: harness-output
  on:
    branch: master
  provider: pages
  repo: DevSnicket/Eunice-harnesses
  skip-cleanup: true
  target-branch: master
install:
  - (cd javascript-analyzer-and-renderer-harness && npm install)
  - (cd Processors && npm install)
  - (cd Renderer && npm install)
language: node_js
node_js:
  - "8.11.2"
notifications:
  email: false
script:
  - ./lint.sh
  - ./test.sh
  - mkdir -p test-coverage && npm install --no-save --prefix test-coverage coveralls@3.0.1 && (cat Processors/test-coverage/lcov.info && cat Renderer/test-coverage/lcov.info) | test-coverage/node_modules/coveralls/bin/coveralls.js
  - ./dogfooding/generate.sh
  - ./harnesses.sh