pool: { vmImage: 'ubuntu-latest' }
steps:
  - task: NodeTool@0
    displayName: Node install
    inputs: { versionSpec: '8.x' }
  - task: Npm@1
    displayName: NPM install
    inputs: { command: 'install' }
  - script: npm run build
    displayName: NPM run build
  - script: npm run harness-publish
    displayName: NPM run harness publish
  - task: Npm@1
    continueOnError: true
    displayName: NPM publish
    inputs:
      command: 'publish'
      publishEndpoint: 'npm.org registry'
  - task: CopyFiles@2
    displayName: packageWithoutScope copy readme
    inputs:
      Contents: 'README.md'
      TargetFolder: 'packageWithoutScope'
  - script: (cd packageWithoutScope && node createPackageJson.js)
    displayName: packageWithoutScope create package JSON
  - task: Npm@1
    continueOnError: true
    displayName: packageWithoutScope NPM publish
    inputs:
      command: 'publish'
      workingDir: 'packageWithoutScope'
      publishEndpoint: 'npm.org registry'
trigger: [ master ]