pool:
  name: $(pool_name)
  vmImage: 'ubuntu-latest'
steps:
  - task: NodeTool@0
    displayName: Node install
    inputs: { versionSpec: '10.x' }
  - script: npm install -g npm@latest
    displayName: update NPM
  - task: Npm@1
    displayName: NPM install
    inputs: { command: 'install' }
  - script: npm run all
    displayName: NPM run all
  - script: >-
      rm -rf gh-pages &&
      git submodule add --force -b gh-pages https://$(github_access_token)@github.com/DevSnicket/devsnicket.github.io.git master &&
      rm -rf gh-pages/eunice/dogfooding &&
      cp -r dogfooding/output gh-pages/eunice/dogfooding &&
      rm -rf gh-pages/eunice/javascript &&
      cp -r harness/output gh-pages/eunice/javascript &&
      rm gh-pages/eunice/javascript/harness.js.map &&
      rm -rf gh-pages/eunice/licensing &&
      mkdir gh-pages/eunice/licensing &&
      cp license gh-pages/eunice/licensing/community-trial.txt &&
      cp third-party-notices.txt gh-pages/eunice/licensing &&
      cd gh-pages &&
      git add . &&
      git config --add user.email grahamdyson@hotmail.com &&
      git config --add user.name "JavaScript harness GitHub pages publish" &&
      if [[ `git status --porcelain` ]]; then
        git commit -m "dogfooding and JavaScript harness";
        git push;
      fi
    displayName: GitHub pages publish
  - task: Npm@1
    continueOnError: true
    displayName: NPM publish
    inputs:
      command: 'publish'
      publishEndpoint: 'npm.org registry'
trigger: [ master ]