pool: { vmImage: 'ubuntu-latest' }
steps:
  - task: NodeTool@0
    displayName: Node install
    inputs: { versionSpec: '10.x' }
  - task: Npm@1
    displayName: NPM install
    inputs: { command: 'install' }
  - script: npm run all
    displayName: NPM run all
  - script: >-
      rm -rf gh-pages &&
      git submodule add --force -b gh-pages https://$(github_access_token)@github.com/DevSnicket/Eunice.git gh-pages &&
      cd gh-pages &&
      rm -f -r * && 
      cp -r ../dogfooding/output/* . &&
      rm harness.js.map &&
      cp -r ../harness/output javascript &&
      rm javascript/harness.js.map &&
      git add . &&
      git config --add user.email grahamdyson@hotmail.com &&
      git config --add user.name "JavaScript harness GitHub pages publish" &&
      if [[ `git status --porcelain` ]]; then
        git commit -m "dogfooding and JavaScript harness";
        git push;
      fi
    displayName: dogfooding and JavaScript harness publish
  - task: Npm@1
    continueOnError: true
    displayName: NPM publish
    inputs:
      command: 'publish'
      publishEndpoint: 'npm.org registry'
  - task: CopyFiles@2
    displayName: packageWithoutScope copy readme
    inputs:
      Contents: |
        LICENCE
        README.md
      TargetFolder: 'packageWithoutScope'
  - script: (cd packageWithoutScope && node createPackageJson.js)
    displayName: packageWithoutScope create package JSON
  - task: Npm@1
    continueOnError: true
    displayName: packageWithoutScope NPM publish
    inputs:
      command: 'publish'
      workingDir: 'packageWithoutScope'
      publishEndpoint: 'npm.org registry'
trigger: [ master ]