jobs:
  include:
    - install: 
        - npm install
      script:
        - npm run lint
        - npm run spellcheck
    - before_install:
        - cd processor-plugins
deploy:
  api_key: $NPM_TOKEN
  email: grahamdyson@hotmail.com
  provider: npm
  skip_cleanup: true
language: node_js
node_js:
  - "8.11.2"
notifications:
  email:
    on_success: never
    on_failure: always