cache: { directories: [ node_modules ] }
deploy:
  api_key: $NPM_TOKEN
  email: grahamdyson@hotmail.com
  provider: npm
install: npm install
language: node_js
node_js: 12
notifications:
  email:
    on_success: never
    on_failure: always
os: linux
script: npm run all