/* Copyright (c) 2019 Graham Dyson. All Rights Reserved.
This library is free software, licensed under the terms of the GNU General Public License as published by the Free Software Foundation, either version 3 of the License, or (at your option) any later version. You should have received a copy of the GNU General Public License along with this program.  If not, see <http://www.gnu.org/licenses/>. */

// cSpell:ignore microtask

const
	browser =
		[
			"AbortController",
			"alert",
			"clearInterval",
			"clearTimeout",
			"Comment",
			"console",
			"CustomEvent",
			"Document",
			"DocumentFragment",
			"DocumentType",
			"DOMError",
			"DOMException",
			"DOMImplementation",
			"DOMParser",
			"DOMPoint",
			"DOMPointReadOnly",
			"DOMRect",
			"Event",
			"EventTarget",
			"MutationObserver",
			"queueMicrotask",
			"Range",
			"setInterval",
			"setTimeout",
			"Text",
			"TextDecoder",
			"TextEncoder",
			"URL",
			"URLSearchParams",
			"window",
		],
	commonjs =
		[
			"__dirname",
			"__filename",
			"module",
			"require",
		],
	nodejs =
		[
			"Buffer",
			"clearImmediate",
			"clearInterval",
			"clearTimeout",
			"console",
			"process",
			"queueMicrotask",
			"setImmediate",
			"setInterval",
			"setTimeout",
			"TextDecoder",
			"TextEncoder",
			"URL",
			"URLSearchParams",
		],
	standard =
		[
			"arguments",
			"Array",
			"ArrayBuffer",
			"AsyncFunction",
			"Atomics",
			"BigInt",
			"BigInt64Array",
			"BigUint64Array",
			"Boolean",
			"DataView",
			"Date",
			"decodeURI",
			"decodeURIComponent",
			"encodeURI",
			"encodeURIComponent",
			"Error",
			"escape",
			"eval",
			"EvalError",
			"Float32Array",
			"Float64Array",
			"Function",
			"GeneratorFunction",
			"Int16Array",
			"Int32Array",
			"Int8Array",
			"Intl",
			"isFinite",
			"isNaN",
			"JSON",
			"Map",
			"Math",
			"Number",
			"Object",
			"parseFloat",
			"parseInt",
			"Promise",
			"Proxy",
			"RangeError",
			"ReferenceError",
			"Reflect",
			"RegExp",
			"Set",
			"SharedArrayBuffer",
			"String",
			"Symbol",
			"SyntaxError",
			"TypeError",
			"Uint16Array",
			"Uint32Array",
			"Uint8Array",
			"Uint8ClampedArray",
			"unescape",
			"URIError",
			"WeakMap",
			"WeakSet",
			"WebAssembly",
		];

module.exports =
	callee =>
		new Set([ ...browser, ...commonjs, ...nodejs, ...standard ])
		.has(callee);