- existing
- [ addFromCall, createDeclarations, createDependsUponIdentifiers, createFunctionDeclaration ]
- [ getItemWhenSingleOrStackItemsWhenMultiple, getParentFromAncestors, getPropertyName, stackItemsWhenMultiple ]