- existing
- [ addFromCall, createDeclarations, createDependsUponIdentifiers, createFunctionDeclaration, parentFunctionsFromAncestors ]
- [ getItemWhenSingleOrStackItemsWhenMultiple, getParentFromAncestors, getPropertyName, stackItemsWhenMultiple ]