- existing
- [ addFromCall, commonjs, createDeclarations, createDependsUponIdentifiers ]
- [ getItemWhenSingleOrStackItemsWhenMultiple, getParentFromAncestors, getPropertyName, parentFunctionsFromAncestors, stackItemsWhenMultiple ]