- existing
- [ addFromCall, createDeclarations, createDependsUponIdentifiers, parentFunctionsFromAncestors ]
- [ getItemWhenSingleOrStackItemsWhenMultiple, getParentFromAncestors, getPropertyName, stackItemsWhenMultiple ]