- existing
- [ addFromCall, commonjs, createDeclarations, createDependsUponIdentifiers ]
- [ getNamesFromDestructureOrIdentifier, getParentFromAncestors, parentFunctionsFromAncestors, stackItemsWhenMultiple ]