- existing
- [ addFromCall, commonjs, createDeclarations, createDependsUponIdentifiers ]
- [ getNamesFromDestructureOrIdentifier, getParentFromAncestors, hasTypeOfFunction, parentFunctionsFromAncestors, stackItemsWhenMultiple ]