- existing
- [ addFromCall, commonjs, createDeclarations, createDependsUponIdentifiers, createItemsProperty, ]
- [ findBlockOrIdentifiableParentInAncestors, getNamesFromDestructureOrIdentifier, getParentFromAncestors, hasTypeOfFunction, stackItemsWhenMultiple ]