-
  - createOrAddToStacksToItemsWithIdentifier
  - createOrAddToStacksUniformly
  - createOrAddToStacksUsingFileSystem
-
  - createStackWhenIdentifierOrItemOrLevelOrAddWhenStack
  - parseCommaSeparated
  - replaceItemsAndInItems