-
  - createOrAddToStacksOfParentMatch
  - createOrAddToStacksUniformly
  - createOrAddToStacksUsingFileSystem
-
  - createStackWhenIdentifierOrItemOrLevelOrAddWhenStack
  - parseCommaSeparated
  - replaceItemsAndInItems