jobs:
  - job: node_10_and_13
    steps:
      - task: NodeTool@0
        displayName: Node install
        inputs: { versionSpec: $(node_version) }
      - task: Npm@1
        displayName: NPM install
        inputs: { command: 'install' }
      - script: npm run all
        displayName: NPM run all
    strategy:
      matrix:
        node_10: { node_version: 10.19 }
        node_13: { node_version: 13.8 }
    workspace: { clean: all }
  - job: node_12
    steps:
      - task: NodeTool@0
        displayName: Node install
        inputs: { versionSpec: 12.16.0 }
      - task: Npm@1
        displayName: NPM install
        inputs: { command: 'install' }
      - script: npm run all
        displayName: NPM run all
      - task: Npm@1
        continueOnError: true
        displayName: NPM publish
        inputs:
          command: 'publish'
          publishEndpoint: 'Azure private NPM'
pool:
  name: $(pool_name)
  vmImage: 'ubuntu-18.04'
trigger: [ master ]