- - javascript
-
  - javascript-analyzer
  - id: processors and renderer
    items:
      - - renderer-test-harness
      -
        - processors
        - renderer
      -
        - dependency-and-structure
        - test-harnesses-processor-plugins
-
  - call-with-process-standard-streams
  - run-tests-from-file-system
  - test-harnesses
-
  - id: jest
    dependencyPermeable: true
    items: [ describe, expect ]