- - "@devsnicket/eunice-javascript"
- - "@devsnicket/eunice-renderer-test-harness"
- - "@devsnicket/eunice-javascript-analyzer"
  - "@devsnicket/eunice-processors"
  - "@devsnicket/eunice-renderer"
- - "@devsnicket/eunice-call-with-process-standard-streams"
  - "@devsnicket/eunice-dependency-and-structure"
  - "@devsnicket/eunice-run-tests-from-file-system"
  - "@devsnicket/eunice-test-harnesses"
  - "@devsnicket/eunice-test-harnesses-processor-plugins"