- - javascript
-
  - javascript-analyzer
  - id: processors and renderer
    dependencyPermeable: true
    items:
      - - renderer-test-harness
      -
        - processors
        - renderer
      -
        - dependency-and-structure
        - test-harnesses-processor-plugins
-
  - call-with-process-standard-streams
  - run-tests-from-file-system
  - test-harnesses
- - id: 3rd party packages
    dependencyPermeable: true
    items:
      - fs-extra
      - id: jest
        dependencyPermeable: true
        items: [ describe, expect ]
      - js-yaml
      - minimist
      - monaco-editor
      - pretty-format
      - react
      - react-dom
      - string-pixel-width
      - webpack