- - existing
- - id: 3rd party packages
    dependencyPermeable: true
    items:
      - fs-extra
      - id: jest
        dependencyPermeable: true
        items: [ describe, expect, test ]
      - js-yaml
      - minimist
      - monaco-editor
      - pretty-format
      - react
      - react-dom
      - string-pixel-width
      - webpack