cache:
  directories: [ node_modules ]
deploy:
  - api_key: $NPM_TOKEN
    email: grahamdyson@hotmail.com
    provider: npm
    skip_cleanup: true
install: [ npm install ]
language: node_js
node_js: [ 8.17.0, 9.11.2, 10.18.0, 11.15.0, 12.14.0 ]
notifications:
  email:
    on_success: never
    on_failure: always
script:
  - npm run all
  - mkdir -p test-coverage && npm install --no-save --prefix test-coverage coveralls@3.0.1 && cat test-coverage/lcov.info | test-coverage/node_modules/coveralls/bin/coveralls.js