cache:
  directories:
    - node_modules
deploy:
  - api_key: $NPM_TOKEN
    email: grahamdyson@hotmail.com
    provider: npm
    skip_cleanup: true
install: 
  - npm install
language: node_js
node_js:
  - "8.11.2"
notifications:
  email:
    on_success: never
    on_failure: always
script:
  - npm run lint
  - npm run spellcheck
  - npm run test
  - mkdir -p test-coverage && npm install --no-save --prefix test-coverage coveralls@3.0.1 && cat test-coverage/lcov.info | test-coverage/node_modules/coveralls/bin/coveralls.js
  - npm run build