on: [push]
jobs:
  ubuntu-latest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with: { submodules: 'true' }
      - uses: actions/setup-node@v3
        with: { node-version: '14' }
      - run: npm install -g npm@7
      - run: npm install
      - run: ./all.sh all ${{ secrets.GITHUB_TOKEN }} ${{ github.repository }}
      - uses: JS-DevTools/npm-publish@v1
        with:
          package: ./javascript/package.json
          token: ${{ secrets.NPM_TOKEN }}
      - uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '3.1.x'
      - uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '5.0.x'
      - run: ./csharp/all.sh
      - run: ./csharp/package/push.sh ${{ secrets.NUGET_TOKEN }}