on: [push]
jobs:
  ubuntu-latest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v3
        with: { node-version: '14' }
      - run: npm install -g npm@7
      - run: npm install
      - run: ./all.sh
      - uses: JS-DevTools/npm-publish@v1
        with:
          package: ./javascript/package.json
          token: ${{ secrets.NPM_TOKEN }}