on: [push, workflow_dispatch]
jobs:
  ubuntu-latest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with: { submodules: 'true' }
      - uses: actions/setup-node@v3
        with: { node-version: '14' }
      - run: npm install -g npm@7
      - run: npm install
      - run: ./all.sh all ${{ secrets.GITHUB_TOKEN }} ${{ github.repository }}
      - if: github.ref == 'refs/heads/master'
        uses: JS-DevTools/npm-publish@v1
        with:
          package: ./javascript/package.json
          token: ${{ secrets.NPM_TOKEN }}
      - name: setup .NET 3.1
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '3.1.x'
      - name: setup .NET 5.0
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '5.0.x'
      - name: setup .NET 6.0
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '6.0.x'
      - name: setup .NET 7.0
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '7.0.x'
      - name: setup .NET 8.0
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.x'
      - run: ./csharp/all.sh
      - if: github.ref == 'refs/heads/master'
        run: ./csharp/package/push.sh ${{ secrets.NUGET_TOKEN }}